### ISSUE TITLE
can I use a baseurl with this theme?

### ISSUE THREAD

**Issue by tomjohnson1492** [CloudCannon/Aviator-Jekyll-Theme#1]
When I try to add a baseurl to the config file, the theme doesn't display correctly.

For example, I added this to the _config.yml file:

```
title: Aviator theme demo
host: 127.0.0.1
port: 4029
baseurl: "/aviatortheme" 
```

When I turn `jekyll serve`, the site doesn't show any images or styles. If I take away the baseurl, it shows fine. I'm not sure why the baseurl isn't working.

**Comment by tomjohnson1492** [comment]
I realize that this theme works well with the cloud cannon infrastructure, so maybe when coding cloud cannon themes you don't include a baseurl?

**Comment by mneumegen** [comment]
Hi @tomjohnson1492,

Yip baseurls's will work, you just need to prefix any linking to assets with the baseurl. For example, line 7 in `_layouts/default.html` would become:

``
<link rel="stylesheet" href="{{ site.baseurl }}/css/normalize.css">
``

**Comment by tomjohnson1492** [comment]
Thanks Mike.
